# Generated by Django 6.0.4 on 2026-05-10 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
