# Generated by Django 6.0.4 on 2026-05-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Tech', 'Tech'), ('Art', 'Art')], default='Coffee', max_length=20),
        ),
    ]
