# Generated by Django 6.0.4 on 2026-05-16 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shop_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
